import { Technology } from '../../src/technologies/technologies/technology';

const rawData = {
    AngularJS: {
        name: 'AngularJS',
        id: '-M5CNXKxy9oNYmEz-cSx',
        url: 'https://cdn.filestackcontent.com/z91tv0taRZ6O3HgtDx8g',
        tags: ['framework', 'javascript'],
        handle: 'z91tv0taRZ6O3HgtDx8g',
    },
    Apache: {
        name: 'Apache',
        id: '-M5CNXKxy9oNYmEz-cSy',
        url: 'https://cdn.filestackcontent.com/dNYZs5SCQBmPDfJ2ZWn5',
        tags: ['php'],
        handle: 'dNYZs5SCQBmPDfJ2ZWn5',
    },
    Appcelerator: {
        name: 'Appcelerator',
        id: '-M5CNXKxy9oNYmEz-cSz',
        url: 'https://cdn.filestackcontent.com/C91r4HSQToyYZfL95kB1',
        tags: ['app', 'mobile'],
        handle: 'C91r4HSQToyYZfL95kB1',
    },
    BackboneJS: {
        name: 'BackboneJS',
        id: '-M5CNXKxy9oNYmEz-cT-',
        url: 'https://cdn.filestackcontent.com/nyxEX40YQW6W6mWqCmyd',
        tags: ['javascript', 'framework'],
        handle: 'nyxEX40YQW6W6mWqCmyd',
    },
    'Amazon Web Services': {
        name: 'Amazon Web Services',
        id: '-M5CNXL0m7wxrwoQiI0r',
        url: 'https://cdn.filestackcontent.com/Knz3wGZQwqWIfjHQF38M',
        tags: ['aws', 'amazon', 'ec2'],
        handle: 'Knz3wGZQwqWIfjHQF38M',
    },
    Bootstrap: {
        name: 'Bootstrap',
        id: '-M5CNXKxy9oNYmEz-cT1',
        url: 'https://cdn.filestackcontent.com/LMNDz25USuKPx2dhrbWV',
        tags: ['css', 'framework', 'css3'],
        handle: 'LMNDz25USuKPx2dhrbWV',
    },
    C: {
        name: 'C',
        id: '-M5CNXKxy9oNYmEz-cT2',
        url: 'https://cdn.filestackcontent.com/JEw4A3YURFagr1ESXT9X',
        tags: ['language'],
        handle: 'JEw4A3YURFagr1ESXT9X',
    },
    Cakephp: {
        name: 'Cakephp',
        id: '-M5CNXKxy9oNYmEz-cT3',
        url: 'https://cdn.filestackcontent.com/4VX5QGMnQ8a3J1yJXhbH',
        tags: ['framework'],
        handle: '4VX5QGMnQ8a3J1yJXhbH',
    },
    Ceylon: {
        name: 'Ceylon',
        id: '-M5CNXKxy9oNYmEz-cT4',
        url: 'https://cdn.filestackcontent.com/fKn5LbrqRQKKAyWgxz2r',
        tags: ['language'],
        handle: 'fKn5LbrqRQKKAyWgxz2r',
    },
    Codeigniter: {
        name: 'Codeigniter',
        id: '-M5CNXKxy9oNYmEz-cT5',
        url: 'https://cdn.filestackcontent.com/2h6fdJQ0TMqGOhhdU0P8',
        tags: ['php', 'framework'],
        handle: '2h6fdJQ0TMqGOhhdU0P8',
    },
    Coffeescript: {
        name: 'Coffeescript',
        id: '-M5CNXKxy9oNYmEz-cT6',
        url: 'https://cdn.filestackcontent.com/4RPlIiSXReibsFo3d4Ih',
        tags: ['javascript', 'language'],
        handle: '4RPlIiSXReibsFo3d4Ih',
    },
    Confluence: {
        name: 'Confluence',
        id: '-M5CNXKxy9oNYmEz-cT7',
        url: 'https://cdn.filestackcontent.com/z7vPw3vJTqixmoKPNEsD',
        handle: 'z7vPw3vJTqixmoKPNEsD',
    },
    'C++': {
        name: 'C++',
        id: '-M5CNXKxy9oNYmEz-cT8',
        url: 'https://cdn.filestackcontent.com/bguzSykRyeCJTDP3SuN0',
        tags: ['language'],
        handle: 'bguzSykRyeCJTDP3SuN0',
    },
    'C#': {
        name: 'C#',
        id: '-M5CNXKxy9oNYmEz-cT9',
        url: 'https://cdn.filestackcontent.com/d99TZI3yRCm9PwVmsikB',
        tags: ['language'],
        handle: 'd99TZI3yRCm9PwVmsikB',
    },
    CSS3: {
        name: 'CSS3',
        id: '-M5CNXKxy9oNYmEz-cTA',
        url: 'https://cdn.filestackcontent.com/qypr8RXQlOeXRa0zNnw1',
        tags: ['language', 'programming'],
        handle: 'qypr8RXQlOeXRa0zNnw1',
    },
    Cucumber: {
        name: 'Cucumber',
        id: '-M5CNXKxy9oNYmEz-cTB',
        url: 'https://cdn.filestackcontent.com/VIwFjwjSpS4wjweCEqAw',
        tags: ['framework'],
        handle: 'VIwFjwjSpS4wjweCEqAw',
    },
    D3JS: {
        name: 'D3JS',
        id: '-M5CNXKxy9oNYmEz-cTC',
        url: 'https://cdn.filestackcontent.com/AH5iqlh9QqGiq57NchkA',
        handle: 'AH5iqlh9QqGiq57NchkA',
    },
    Django: {
        name: 'Django',
        id: '-M5CNXKyRIMA4Xys7zty',
        url: 'https://cdn.filestackcontent.com/czqMUWLQEyyN3cTF9Ym7',
        handle: 'czqMUWLQEyyN3cTF9Ym7',
    },
    Docker: {
        name: 'Docker',
        id: '-M5CNXKyRIMA4Xys7ztz',
        url: 'https://cdn.filestackcontent.com/e1wA6stoRkqcCoLKHoog',
        tags: ['platform', 'deploy'],
        handle: 'e1wA6stoRkqcCoLKHoog',
    },
    Doctrine: {
        name: 'Doctrine',
        id: '-M5CNXKyRIMA4Xys7zu-',
        url: 'https://cdn.filestackcontent.com/nloR7i4CTaBPDzlxUO3Q',
        handle: 'nloR7i4CTaBPDzlxUO3Q',
    },
    'Dot-net': {
        name: 'Dot-net',
        id: '-M5CNXKyRIMA4Xys7zu0',
        url: 'https://cdn.filestackcontent.com/hWoqt0pGTLaFNvz4baby',
        tags: ['framework'],
        handle: 'hWoqt0pGTLaFNvz4baby',
    },
    Drupal: {
        name: 'Drupal',
        id: '-M5CNXKyRIMA4Xys7zu1',
        url: 'https://cdn.filestackcontent.com/KZIpViqRQql4SlnlTM4h',
        tags: ['cms'],
        handle: 'KZIpViqRQql4SlnlTM4h',
    },
    Elm: {
        name: 'Elm',
        id: '-M5CNXKyRIMA4Xys7zu2',
        url: 'https://cdn.filestackcontent.com/bcfiTlM9T0eHqax2hsGH',
        tags: ['framework'],
        handle: 'bcfiTlM9T0eHqax2hsGH',
    },
    Erlang: {
        name: 'Erlang',
        id: '-M5CNXKyRIMA4Xys7zu3',
        url: 'https://cdn.filestackcontent.com/XaR3ooL4RsiQG9cyguAJ',
        handle: 'XaR3ooL4RsiQG9cyguAJ',
    },
    Express: {
        name: 'Express',
        id: '-MHL_gJz4yYzaoL0hv62',
        url: 'https://cdn.filestackcontent.com/iDzQGSDnTRatv2Hurizx',
        tags: ['framework', 'nodejs', 'backend'],
        handle: 'iDzQGSDnTRatv2Hurizx',
    },
    Git: {
        name: 'Git',
        id: '-M5CNXKyRIMA4Xys7zu5',
        url: 'https://cdn.filestackcontent.com/WjA6qId8QvWLa0iW00sL',
        tags: ['version-control'],
        handle: 'WjA6qId8QvWLa0iW00sL',
    },
    Github: {
        name: 'Github',
        id: '-M5CNXKyRIMA4Xys7zu6',
        url: 'https://cdn.filestackcontent.com/drg3VJ4ISTuFtpVrvpFk',
        tags: ['version-control'],
        handle: 'drg3VJ4ISTuFtpVrvpFk',
    },
    Gitlab: {
        name: 'Gitlab',
        id: '-M5CNXKyRIMA4Xys7zu7',
        url: 'https://cdn.filestackcontent.com/g8GexytToiPahu9Q7vSA',
        tags: ['version-control'],
        handle: 'g8GexytToiPahu9Q7vSA',
    },
    Go: {
        name: 'Go',
        id: '-M5CNXKyRIMA4Xys7zu8',
        url: 'https://cdn.filestackcontent.com/K7z1dYsESrWsQ19wjNdd',
        tags: ['language'],
        handle: 'K7z1dYsESrWsQ19wjNdd',
    },
    Gradle: {
        name: 'Gradle',
        id: '-M5CNXKyRIMA4Xys7zu9',
        url: 'https://cdn.filestackcontent.com/fgtxwHKbReSx0EHz39ir',
        tags: ['task-runner'],
        handle: 'fgtxwHKbReSx0EHz39ir',
    },
    Grunt: {
        name: 'Grunt',
        id: '-M5CNXKyRIMA4Xys7zuA',
        url: 'https://cdn.filestackcontent.com/YTlq6BTTnCDxoNpy8Bqm',
        tags: ['task-runner', 'nodejs'],
        handle: 'YTlq6BTTnCDxoNpy8Bqm',
    },
    Gulp: {
        name: 'Gulp',
        id: '-M5CNXKyRIMA4Xys7zuB',
        url: 'https://cdn.filestackcontent.com/D4FRjln3TLOgxYitJKHz',
        tags: ['task-runner', 'nodejs'],
        handle: 'D4FRjln3TLOgxYitJKHz',
    },
    HTML5: {
        name: 'HTML5',
        id: '-M5CNXKyRIMA4Xys7zuC',
        url: 'https://cdn.filestackcontent.com/Le6p4xlUQkW189RcHcBT',
        tags: ['programming', 'language'],
        handle: 'Le6p4xlUQkW189RcHcBT',
    },
    Java: {
        name: 'Java',
        id: '-M5CNXKyRIMA4Xys7zuD',
        url: 'https://cdn.filestackcontent.com/LietCzaSTEmfZTdvgpjC',
        tags: ['programming', 'language'],
        handle: 'LietCzaSTEmfZTdvgpjC',
    },
    Jasmine: {
        name: 'Jasmine',
        id: '-M5CNXKyRIMA4Xys7zuE',
        url: 'https://cdn.filestackcontent.com/LkBi9xGDReSVfB33p826',
        tags: ['testing'],
        handle: 'LkBi9xGDReSVfB33p826',
    },
    Javascript: {
        name: 'Javascript',
        id: '-M5CNXKyRIMA4Xys7zuF',
        url: 'https://cdn.filestackcontent.com/6ZrIEmWRgycFn9smUNzN',
        tags: ['programming', 'language'],
        handle: '6ZrIEmWRgycFn9smUNzN',
    },
    Jeet: {
        name: 'Jeet',
        id: '-M5CNXKyRIMA4Xys7zuG',
        url: 'https://cdn.filestackcontent.com/YoK0AovxTTO9d0V8M0r1',
        tags: ['framework', 'css'],
        handle: 'YoK0AovxTTO9d0V8M0r1',
    },
    jQuery: {
        name: 'jQuery',
        id: '-M5CNXKyRIMA4Xys7zuH',
        url: 'https://cdn.filestackcontent.com/u7WyAbPmTC2aMbvKnJGb',
        tags: ['library', 'javascript'],
        handle: 'u7WyAbPmTC2aMbvKnJGb',
    },
    Krakenjs: {
        name: 'Krakenjs',
        id: '-M5CNXKyRIMA4Xys7zuI',
        url: 'https://cdn.filestackcontent.com/vRdXw2TVSPOuoAToe5qT',
        tags: ['nodejs', 'framework'],
        handle: 'vRdXw2TVSPOuoAToe5qT',
    },
    Laravel: {
        name: 'Laravel',
        id: '-M5CNXKyRIMA4Xys7zuJ',
        url: 'https://cdn.filestackcontent.com/yUqfG0KRB6nc2FhCHZnQ',
        tags: ['php', 'framework'],
        handle: 'yUqfG0KRB6nc2FhCHZnQ',
    },
    Less: {
        name: 'Less',
        id: '-M5CNXKyRIMA4Xys7zuK',
        url: 'https://cdn.filestackcontent.com/rdQ4RSZFSu0GAUclg0Gx',
        tags: ['css', 'pre-processor'],
        handle: 'rdQ4RSZFSu0GAUclg0Gx',
    },
    Meteor: {
        name: 'Meteor',
        id: '-M5CNXKyRIMA4Xys7zuL',
        url: 'https://cdn.filestackcontent.com/gKe5LEwRoCYvT1smAprL',
        tags: ['javascript'],
        handle: 'gKe5LEwRoCYvT1smAprL',
    },
    Mocha: {
        name: 'Mocha',
        id: '-M5CNXKzkSuZBbUdiuEp',
        url: 'https://cdn.filestackcontent.com/Jp5nvbhjST20c6YlURUx',
        tags: ['testing'],
        handle: 'Jp5nvbhjST20c6YlURUx',
    },
    MongoDB: {
        name: 'MongoDB',
        id: '-M5CNXKzkSuZBbUdiuEq',
        url: 'https://cdn.filestackcontent.com/vdbehS4NTGKDNVsx9d55',
        tags: ['database'],
        handle: 'vdbehS4NTGKDNVsx9d55',
    },
    Moodle: {
        name: 'Moodle',
        id: '-M5CNXKzkSuZBbUdiuEr',
        url: 'https://cdn.filestackcontent.com/el55cbEbQJuThVXWLcSC',
        tags: ['platform'],
        handle: 'el55cbEbQJuThVXWLcSC',
    },
    Mysql: {
        name: 'Mysql',
        id: '-M5CNXKzkSuZBbUdiuEs',
        url: 'https://cdn.filestackcontent.com/r1WMe7YhQfed0bbTZV24',
        tags: ['database', 'language'],
        handle: 'r1WMe7YhQfed0bbTZV24',
    },
    Nginx: {
        name: 'Nginx',
        id: '-M5CNXKzkSuZBbUdiuEt',
        url: 'https://cdn.filestackcontent.com/fZ8pgJ4RdSv3mlWbVZvg',
        tags: ['server'],
        handle: 'fZ8pgJ4RdSv3mlWbVZvg',
    },
    NodeJS: {
        name: 'NodeJS',
        id: '-M5CNXKzkSuZBbUdiuEu',
        url: 'https://cdn.filestackcontent.com/onSEtBpQpmAtQP2N9fFL',
        tags: ['javascript', 'language'],
        handle: 'onSEtBpQpmAtQP2N9fFL',
    },
    PHP: {
        name: 'PHP',
        id: '-M5CNXKzkSuZBbUdiuEv',
        url: 'https://cdn.filestackcontent.com/NjHy5aiASQCvAYNTZs1R',
        tags: ['programming', 'language'],
        handle: 'NjHy5aiASQCvAYNTZs1R',
    },
    PhpStorm: {
        name: 'PhpStorm',
        id: '-M5CNXKzkSuZBbUdiuEw',
        url: 'https://cdn.filestackcontent.com/B5XI4AAjQvSRSu2Sw1UO',
        tags: ['editor'],
        handle: 'B5XI4AAjQvSRSu2Sw1UO',
    },
    Protractor: {
        name: 'Protractor',
        id: '-M5CNXKzkSuZBbUdiuEx',
        url: 'https://cdn.filestackcontent.com/FDVqaNWWQ9yqfx5CRKYA',
        tags: ['framework', 'javascript'],
        handle: 'FDVqaNWWQ9yqfx5CRKYA',
    },
    PostgreSQL: {
        name: 'PostgreSQL',
        id: '-M5CNXKzkSuZBbUdiuEy',
        url: 'https://cdn.filestackcontent.com/o0yFHIQyQTOVhoi6O1V7',
        tags: ['database'],
        handle: 'o0yFHIQyQTOVhoi6O1V7',
    },
    Python: {
        name: 'Python',
        id: '-M5CNXKzkSuZBbUdiuEz',
        url: 'https://cdn.filestackcontent.com/jiclpS0yRhySvhSlLDGA',
        tags: ['programming', 'language'],
        handle: 'jiclpS0yRhySvhSlLDGA',
    },
    Rails: {
        name: 'Rails',
        id: '-M5CNXKzkSuZBbUdiuF-',
        url: 'https://cdn.filestackcontent.com/iWYqNN3HRSuXA15UplJZ',
        tags: ['framework'],
        handle: 'iWYqNN3HRSuXA15UplJZ',
    },
    React: {
        name: 'React',
        id: '-M5CNXKzkSuZBbUdiuF0',
        url: 'https://cdn.filestackcontent.com/KKn2Q218TaeF51faVayy',
        tags: ['framework'],
        handle: 'KKn2Q218TaeF51faVayy',
    },
    Redis: {
        name: 'Redis',
        id: '-M5CNXKzkSuZBbUdiuF1',
        url: 'https://cdn.filestackcontent.com/zWndpSOgSRmGO6iEZS4w',
        tags: ['server'],
        handle: 'zWndpSOgSRmGO6iEZS4w',
    },
    Ruby: {
        name: 'Ruby',
        id: '-M5CNXKzkSuZBbUdiuF2',
        url: 'https://cdn.filestackcontent.com/sCQlQ7I4QqaXVKQDwJnd',
        tags: ['programming', 'language'],
        handle: 'sCQlQ7I4QqaXVKQDwJnd',
    },
    Rubymine: {
        name: 'Rubymine',
        id: '-M5CNXKzkSuZBbUdiuF3',
        url: 'https://cdn.filestackcontent.com/cMSUveewRi2MLOXV8iOc',
        tags: ['editor'],
        handle: 'cMSUveewRi2MLOXV8iOc',
    },
    Sass: {
        name: 'Sass',
        id: '-M5CNXKzkSuZBbUdiuF4',
        url: 'https://cdn.filestackcontent.com/s2vrnWamR5cqvV6IGHgR',
        tags: ['pre-processor', 'css'],
        handle: 's2vrnWamR5cqvV6IGHgR',
    },
    Sequelize: {
        name: 'Sequelize',
        id: '-M5CNXKzkSuZBbUdiuF5',
        url: 'https://cdn.filestackcontent.com/pz0rjgYsSjCCosG5mycZ',
        tags: ['database', 'language'],
        handle: 'pz0rjgYsSjCCosG5mycZ',
    },
    Slack: {
        name: 'Slack',
        id: '-M5CNXKzkSuZBbUdiuF6',
        url: 'https://cdn.filestackcontent.com/dtcAerpxTomngKKeX4Gj',
        tags: ['chat'],
        handle: 'dtcAerpxTomngKKeX4Gj',
    },
    SSH: {
        name: 'SSH',
        id: '-M5CNXKzkSuZBbUdiuF7',
        url: 'https://cdn.filestackcontent.com/ofFhg112T1SA71FxjKVq',
        tags: ['security'],
        handle: 'ofFhg112T1SA71FxjKVq',
    },
    Stylus: {
        name: 'Stylus',
        id: '-M5CNXKzkSuZBbUdiuF8',
        url: 'https://cdn.filestackcontent.com/PR39NDOQPSvDHwAmpTYQ',
        tags: ['css', 'pre-processor'],
        handle: 'PR39NDOQPSvDHwAmpTYQ',
    },
    Swift: {
        name: 'Swift',
        id: '-M5CNXKzkSuZBbUdiuF9',
        url: 'https://cdn.filestackcontent.com/SzObnVUWTR6gUqzengpd',
        tags: ['language', 'ios', 'iphone', 'ipad', 'mac', 'ipod', 'emac', 'apple', 'mobile'],
        handle: 'SzObnVUWTR6gUqzengpd',
    },
    Symfony: {
        name: 'Symfony',
        id: '-M5CNXKzkSuZBbUdiuFA',
        url: 'https://cdn.filestackcontent.com/e6SD3ndcQouZdZiAT3oX',
        tags: ['framework', 'php'],
        handle: 'e6SD3ndcQouZdZiAT3oX',
    },
    Tomcat: {
        name: 'Tomcat',
        id: '-M5CNXKzkSuZBbUdiuFB',
        url: 'https://cdn.filestackcontent.com/qtZHgFNnRcurwKj8syUN',
        tags: ['server'],
        handle: 'qtZHgFNnRcurwKj8syUN',
    },
    Travis: {
        name: 'Travis',
        id: '-M5CNXKzkSuZBbUdiuFC',
        url: 'https://cdn.filestackcontent.com/fYIK1L3qQGGQPrm2SErW',
        tags: ['platform', 'integration'],
        handle: 'fYIK1L3qQGGQPrm2SErW',
    },
    Trello: {
        name: 'Trello',
        id: '-M5CNXKzkSuZBbUdiuFD',
        url: 'https://cdn.filestackcontent.com/79nYrsi7SgabIJZPMYYR',
        tags: ['platform', 'organize'],
        handle: '79nYrsi7SgabIJZPMYYR',
    },
    Typescript: {
        name: 'Typescript',
        id: '-M5CNXKzkSuZBbUdiuFE',
        url: 'https://cdn.filestackcontent.com/VIF9M8ebQjukQ4oqAkdP',
        tags: ['programming', 'transpiler'],
        handle: 'VIF9M8ebQjukQ4oqAkdP',
    },
    VIM: {
        name: 'VIM',
        id: '-M5CNXKzkSuZBbUdiuFF',
        url: 'https://cdn.filestackcontent.com/gKtThJFRGmLcPq6fxzRt',
        tags: ['editor'],
        handle: 'gKtThJFRGmLcPq6fxzRt',
    },
    vueJS: {
        name: 'vueJS',
        id: '-M5CNXKzkSuZBbUdiuFG',
        url: 'https://cdn.filestackcontent.com/qXCCT75xQk6lQXMic8zt',
        tags: ['framework'],
        handle: 'qXCCT75xQk6lQXMic8zt',
    },
    Webpack: {
        name: 'Webpack',
        id: '-M5CNXL-f1z-fEZ3rc-9',
        url: 'https://cdn.filestackcontent.com/CW1t8ICQ7Sjg7UStO36B',
        tags: ['package', 'manager'],
        handle: 'CW1t8ICQ7Sjg7UStO36B',
    },
    Wordpress: {
        name: 'Wordpress',
        id: '-M5CNXL-f1z-fEZ3rc-A',
        url: 'https://cdn.filestackcontent.com/wIbkmz2qRimuSjXPBsfV',
        tags: ['cms'],
        handle: 'wIbkmz2qRimuSjXPBsfV',
    },
    Yii: {
        name: 'Yii',
        id: '-M5CNXL-f1z-fEZ3rc-B',
        url: 'https://cdn.filestackcontent.com/TUXTxfzIQripKmLlBN3k',
        tags: ['php', 'framework'],
        handle: 'TUXTxfzIQripKmLlBN3k',
    },
    Zend: {
        name: 'Zend',
        id: '-M5CNXL-f1z-fEZ3rc-C',
        url: 'https://cdn.filestackcontent.com/gCqlLs3HRVOIBii6DllF',
        tags: ['php', 'framework'],
        handle: 'gCqlLs3HRVOIBii6DllF',
    },
    'Objective C': {
        name: 'Objective C',
        id: '-M5CNXL-f1z-fEZ3rc-D',
        url: 'https://cdn.filestackcontent.com/bWD9MCUOTdOCm2hEYOzC',
        tags: ['language', 'ios', 'iphone', 'ipad', 'mac', 'ipod', 'emac', 'apple', 'mobile'],
        handle: 'bWD9MCUOTdOCm2hEYOzC',
    },
    Elixir: {
        name: 'Elixir',
        id: '-M5CNXL-f1z-fEZ3rc-E',
        url: 'https://cdn.filestackcontent.com/s4u8oVO2SIOei6OdZ4yN',
        tags: ['scale', 'maintenable'],
        handle: 's4u8oVO2SIOei6OdZ4yN',
    },
    Perl: {
        name: 'Perl',
        id: '-M5CNXL-f1z-fEZ3rc-F',
        url: 'https://cdn.filestackcontent.com/cqfAVB1fRU6BDAIKSlSZ',
        handle: 'cqfAVB1fRU6BDAIKSlSZ',
    },
    R: {
        name: 'R',
        id: '-M5CNXL-f1z-fEZ3rc-G',
        url: 'https://cdn.filestackcontent.com/FGxWs4y2R5KJzvR3Waho',
        handle: 'FGxWs4y2R5KJzvR3Waho',
    },
    Matlab: {
        name: 'Matlab',
        id: '-M5CNXL-f1z-fEZ3rc-H',
        url: 'https://cdn.filestackcontent.com/srAB7FE9RCK2XxBKXVOF',
        handle: 'srAB7FE9RCK2XxBKXVOF',
    },
    Scratch: {
        name: 'Scratch',
        id: '-M5CNXL-f1z-fEZ3rc-I',
        url: 'https://cdn.filestackcontent.com/d9MfoFLrStCF5TK8nyPM',
        handle: 'd9MfoFLrStCF5TK8nyPM',
    },
    Firebase: {
        name: 'Firebase',
        id: '-M5CNXL-f1z-fEZ3rc-J',
        url: 'https://cdn.filestackcontent.com/5zkrSXKvR0GB5Md6m3ag',
        tags: ['database', 'google', 'react', 'realtime'],
        handle: '5zkrSXKvR0GB5Md6m3ag',
    },
    Arduino: {
        name: 'Arduino',
        id: '-M5CNXL-f1z-fEZ3rc-K',
        url: 'https://cdn.filestackcontent.com/kYmZL2UxSbSNn5EFl5mJ',
        tags: ['uno', 'robot', 'electronics', 'pwm', 'raspberry'],
        handle: 'kYmZL2UxSbSNn5EFl5mJ',
    },
    Scala: {
        name: 'Scala',
        id: '-M5CNXL-f1z-fEZ3rc-L',
        url: 'https://cdn.filestackcontent.com/ysoQ6ob3RMPhVCTCDYzA',
        handle: 'ysoQ6ob3RMPhVCTCDYzA',
    },
    Kotlin: {
        name: 'Kotlin',
        id: '-M5CNXL-f1z-fEZ3rc-M',
        url: 'https://cdn.filestackcontent.com/1tMlVU1QQvm8sPzOsWKn',
        handle: '1tMlVU1QQvm8sPzOsWKn',
    },
    Azure: {
        name: 'Azure',
        id: '-M5CNXL-f1z-fEZ3rc-N',
        url: 'https://cdn.filestackcontent.com/CJSGv1XtS9m2sKyqSg0C',
        tags: ['microsoft'],
        handle: 'CJSGv1XtS9m2sKyqSg0C',
    },
    'Google Cloud': {
        name: 'Google Cloud',
        id: '-MF-zX85INr9X5I_nVd3',
        url: 'https://cdn.filestackcontent.com/vMzg102JTpCCm80t7ddk',
        tags: ['information nuagique', 'GCP', 'Cloud', 'google'],
        handle: 'vMzg102JTpCCm80t7ddk',
    },
    Bluetooth: {
        name: 'Bluetooth',
        id: '-M5CNXL-f1z-fEZ3rc-P',
        url: 'https://cdn.filestackcontent.com/L2xeAPvQTq6T9lnsTCwx',
        tags: ['connect', 'wifi'],
        handle: 'L2xeAPvQTq6T9lnsTCwx',
    },
    Ionic: {
        name: 'Ionic',
        id: '-M5CNXL-f1z-fEZ3rc-Q',
        url: 'https://cdn.filestackcontent.com/EfVgl0yHSauUOoTkTvLo',
        handle: 'EfVgl0yHSauUOoTkTvLo',
    },
    Rust: {
        name: 'Rust',
        id: '-M5CNXL-f1z-fEZ3rc-R',
        url: 'https://cdn.filestackcontent.com/z7rCQD8rQcqsnwWBAVyg',
        tags: ['Mozilla', 'C++', 'Cplusplus'],
        handle: 'z7rCQD8rQcqsnwWBAVyg',
    },
    'Raspberry Pi': {
        name: 'Raspberry Pi',
        id: '-M5CNXL-f1z-fEZ3rc-S',
        url: 'https://cdn.filestackcontent.com/qfFkSxQRaSKroE563CXi',
        tags: ['micro', 'board', 'arduino'],
        handle: 'qfFkSxQRaSKroE563CXi',
    },
    Yarn: {
        name: 'Yarn',
        id: '-M5CNXL-f1z-fEZ3rc-T',
        url: 'https://cdn.filestackcontent.com/WqduN5psTbaJyGkUZRzb',
        tags: ['javascript', 'npm', 'resources'],
        handle: 'WqduN5psTbaJyGkUZRzb',
    },
    SQL: {
        name: 'SQL',
        id: '-M5CNXL-f1z-fEZ3rc-U',
        url: 'https://cdn.filestackcontent.com/01Vr9vuKTGqaswneE45A',
        tags: ['database', 'php'],
        handle: '01Vr9vuKTGqaswneE45A',
    },
    'T-SQL': {
        name: 'T-SQL',
        id: '-M5CNXL-f1z-fEZ3rc-V',
        url: 'https://cdn.filestackcontent.com/T06u2l2nTjGDVWlOd7Md',
        tags: ['microsoft'],
        handle: 'T06u2l2nTjGDVWlOd7Md',
    },
    Prestashop: {
        name: 'Prestashop',
        id: '-M5CNXL-f1z-fEZ3rc-W',
        url: 'https://cdn.filestackcontent.com/04YUjrdTT1yeqj8kOxO4',
        tags: ['store', 'eshop'],
        handle: '04YUjrdTT1yeqj8kOxO4',
    },
    Magento: {
        name: 'Magento',
        id: '-M5CNXL-f1z-fEZ3rc-X',
        url: 'https://cdn.filestackcontent.com/tAu1OidHQ4ybKKaOrzPC',
        tags: ['commerce', 'sell'],
        handle: 'tAu1OidHQ4ybKKaOrzPC',
    },
    Typo3: {
        name: 'Typo3',
        id: '-M5CNXL-f1z-fEZ3rc-Y',
        url: 'https://cdn.filestackcontent.com/LKdAHsHaTFK1JVoopw2r',
        tags: ['CMS', 'Management'],
        handle: 'LKdAHsHaTFK1JVoopw2r',
    },
    SEO: {
        name: 'SEO',
        id: '-M5CNXL-f1z-fEZ3rc-Z',
        url: 'https://cdn.filestackcontent.com/6zKoWYTVTLOAcVYTvR5c',
        tags: ['Google', 'Search', 'DuckDuckGo', 'Qwant', 'Yahoo', 'Bing'],
        handle: '6zKoWYTVTLOAcVYTvR5c',
    },
    Couchbase: {
        name: 'Couchbase',
        id: '-M5CNXL-f1z-fEZ3rc-_',
        url: 'https://cdn.filestackcontent.com/r6kZRDkIRbSunFNvdG4O',
        handle: 'r6kZRDkIRbSunFNvdG4O',
    },
    Hadoop: {
        name: 'Hadoop',
        id: '-M5CNXL-f1z-fEZ3rc-a',
        url: 'https://cdn.filestackcontent.com/CfoI721nTZW10DDCZLgs',
        tags: ['Hadoop'],
        handle: 'CfoI721nTZW10DDCZLgs',
    },
    NoSQL: {
        name: 'NoSQL',
        id: '-M5CNXL-f1z-fEZ3rc-b',
        url: 'https://cdn.filestackcontent.com/KFLGryF7RiCv2w8k3ZOn',
        tags: ['NoSQL'],
        handle: 'KFLGryF7RiCv2w8k3ZOn',
    },
    'Java JEE': {
        name: 'Java JEE',
        id: '-M5CNXL-f1z-fEZ3rc-c',
        url: 'https://cdn.filestackcontent.com/6P453fi7T5auYusJJVKt',
        tags: ['Java', 'JEE', 'Java EE'],
        handle: '6P453fi7T5auYusJJVKt',
    },
    Redshift: {
        name: 'Redshift',
        id: '-M5CNXL-f1z-fEZ3rc-d',
        url: 'https://cdn.filestackcontent.com/6Sys6muRYW4EBw1Ahxew',
        tags: ['Rendering'],
        handle: '6Sys6muRYW4EBw1Ahxew',
    },
    'Amazon EMR': {
        name: 'Amazon EMR',
        id: '-M5CNXL0m7wxrwoQiI0Z',
        url: 'https://cdn.filestackcontent.com/bB0ViNG3SZiTclkdhvGo',
        tags: ['Amazon'],
        handle: 'bB0ViNG3SZiTclkdhvGo',
    },
    Xamarin: {
        name: 'Xamarin',
        id: '-M5CNXL0m7wxrwoQiI0_',
        url: 'https://cdn.filestackcontent.com/ZdnHNqo3Q3W4QH2saynt',
        tags: ['Android'],
        handle: 'ZdnHNqo3Q3W4QH2saynt',
    },
    Gunicorn: {
        name: 'Gunicorn',
        id: '-M5CNXL0m7wxrwoQiI0a',
        url: 'https://cdn.filestackcontent.com/FW5HXNtlTJeMex0bypoP',
        handle: 'FW5HXNtlTJeMex0bypoP',
    },
    Flask: {
        name: 'Flask',
        id: '-M5CNXL0m7wxrwoQiI0b',
        url: 'https://cdn.filestackcontent.com/9jlsa0F3TUmFi1e1hhuw',
        tags: ['tag n°1', 'tag n°2', 'tag n°3'],
        handle: '9jlsa0F3TUmFi1e1hhuw',
    },
    RxJS: {
        name: 'RxJS',
        id: '-M5CNXL0m7wxrwoQiI0c',
        url: 'https://cdn.filestackcontent.com/b3m5c4ZSN2W9t7gwNFvA',
        handle: 'b3m5c4ZSN2W9t7gwNFvA',
    },
    Ansible: {
        name: 'Ansible',
        id: '-M5CNXL0m7wxrwoQiI0d',
        url: 'https://cdn.filestackcontent.com/OqwTtbhQQaK8Q5jcEnQw',
        tags: ['tag n°1', 'tag n°2', 'tag n°3'],
        handle: 'OqwTtbhQQaK8Q5jcEnQw',
    },
    'API Platform': {
        name: 'API Platform',
        id: '-M5CNXL0m7wxrwoQiI0e',
        url: 'https://cdn.filestackcontent.com/R2Aa98LWTfG30vGMz3QL',
        tags: ['API Platform', 'Symfony', 'php'],
        handle: 'R2Aa98LWTfG30vGMz3QL',
    },
    Cobol: {
        name: 'Cobol',
        id: '-M5CNXL0m7wxrwoQiI0f',
        url: 'https://cdn.filestackcontent.com/9UahK0S1SFaE1aDUpZsG',
        tags: ['cobol'],
        handle: '9UahK0S1SFaE1aDUpZsG',
    },
    ThreeJS: {
        name: 'ThreeJS',
        id: '-M5CNXL0m7wxrwoQiI0g',
        url: 'https://cdn.filestackcontent.com/ptrt2YbKQhKfDiN6ppo2',
        tags: ['threejs'],
        handle: 'ptrt2YbKQhKfDiN6ppo2',
    },
    Leaflet: {
        name: 'Leaflet',
        id: '-M5CNXL0m7wxrwoQiI0h',
        url: 'https://cdn.filestackcontent.com/2WArh6hSHqXx182mhrtI',
        handle: '2WArh6hSHqXx182mhrtI',
    },
    Flow: {
        name: 'Flow',
        id: '-M5CNXL0m7wxrwoQiI0i',
        url: 'https://cdn.filestackcontent.com/gppiCgz1S12BwtueMkAO',
        handle: 'gppiCgz1S12BwtueMkAO',
    },
    Geoserver: {
        name: 'Geoserver',
        id: '-M5CNXL0m7wxrwoQiI0j',
        url: 'https://cdn.filestackcontent.com/Qz8AR4jvTSytQe1f2EDl',
        handle: 'Qz8AR4jvTSytQe1f2EDl',
    },
    Prettier: {
        name: 'Prettier',
        id: '-M5CNXL0m7wxrwoQiI0k',
        url: 'https://cdn.filestackcontent.com/7wKIQs5NSqewn7yVoFyD',
        handle: '7wKIQs5NSqewn7yVoFyD',
    },
    MariaDB: {
        name: 'MariaDB',
        id: '-M5CNXL0m7wxrwoQiI0l',
        url: 'https://cdn.filestackcontent.com/wO01YzqzSHebc7VZkhWj',
        tags: ['BDD'],
        handle: 'wO01YzqzSHebc7VZkhWj',
    },
    iOS: {
        name: 'iOS',
        id: '-M5CNXL0m7wxrwoQiI0m',
        url: 'https://cdn.filestackcontent.com/sAJjw8E4SyyVM3WBNg7B',
        tags: ['ios', 'apple'],
        handle: 'sAJjw8E4SyyVM3WBNg7B',
    },
    'React Native': {
        name: 'React Native',
        id: '-M5CNXL0m7wxrwoQiI0n',
        url: 'https://cdn.filestackcontent.com/8XgD9xWsSW6zEp1yETWb',
        handle: '8XgD9xWsSW6zEp1yETWb',
    },
    Terraform: {
        name: 'Terraform',
        id: '-M5CNXL0m7wxrwoQiI0o',
        url: 'https://cdn.filestackcontent.com/KXhQAvDVT3uNHngIVL0W',
        handle: 'KXhQAvDVT3uNHngIVL0W',
    },
    Elasticsearch: {
        name: 'Elasticsearch',
        id: '-M5CNXL0m7wxrwoQiI0p',
        url: 'https://cdn.filestackcontent.com/sp22aYqfRLmfh9TSR6Pa',
        tags: ['tag n°1', 'tag n°2', 'tag n°3'],
        handle: 'sp22aYqfRLmfh9TSR6Pa',
    },
    Joomla: {
        name: 'Joomla',
        id: '-M5CNXL0m7wxrwoQiI0q',
        url: 'https://cdn.filestackcontent.com/fuLzNCv0Sq2eWsiaXnzN',
        tags: ['cms', 'wordpress', 'php'],
        handle: 'fuLzNCv0Sq2eWsiaXnzN',
    },
    SAP: {
        name: 'SAP',
        id: '-M5CNXL0m7wxrwoQiI0s',
        url: 'https://cdn.filestackcontent.com/Md82glPpRgCc1RpLfXSj',
        tags: ['SAP', 'ERP', 'PROGICIEL'],
        handle: 'Md82glPpRgCc1RpLfXSj',
    },
    LabVIEW: {
        name: 'LabVIEW',
        id: '-M5CNXL0m7wxrwoQiI0t',
        url: 'https://cdn.filestackcontent.com/FTXizyVqSqbnsvroHHxg',
        tags: ['LabVIEW', 'benchmark tool'],
        handle: 'FTXizyVqSqbnsvroHHxg',
    },
    RabbitMQ: {
        name: 'RabbitMQ',
        id: '-M5CNXL0m7wxrwoQiI0u',
        url: 'https://cdn.filestackcontent.com/tqIiG07oSqmCwMHEba6e',
        tags: ['RabbitMQ', 'Rabbit', 'rabbitmq'],
        handle: 'tqIiG07oSqmCwMHEba6e',
    },
    Kubernetes: {
        name: 'Kubernetes',
        id: '-M5CNXL0m7wxrwoQiI0v',
        url: 'https://cdn.filestackcontent.com/pjn1DZiBScmrNE1o8sAE',
        tags: ['Kubernetes', 'k8s', 'kubernetes'],
        handle: 'pjn1DZiBScmrNE1o8sAE',
    },
    Angular: {
        name: 'Angular',
        id: '-M5CNXL0m7wxrwoQiI0w',
        url: 'https://cdn.filestackcontent.com/tBUZg8ViRQqokhDJwCHC',
        tags: ['tag n°1', 'tag n°2', 'tag n°3'],
        handle: 'tBUZg8ViRQqokhDJwCHC',
    },
    Windev: {
        name: 'Windev',
        id: '-M5CNXL0m7wxrwoQiI0x',
        url: 'https://cdn.filestackcontent.com/TTtw6WdTSxilUmLZW4pq',
        tags: ['Windows'],
        handle: 'TTtw6WdTSxilUmLZW4pq',
    },
    'Report One': {
        name: 'Report One',
        id: '-M5CNXL0m7wxrwoQiI0y',
        url: 'https://cdn.filestackcontent.com/RzpcTRCCQoBDLTvLqs22',
        tags: ['reportone', 'report one', 'report One', 'Report One'],
        handle: 'RzpcTRCCQoBDLTvLqs22',
    },
    Eagle: {
        name: 'Eagle',
        id: '-M5CNXL0m7wxrwoQiI0z',
        url: 'https://cdn.filestackcontent.com/vnVtmKd5TNecBFiCow1z',
        tags: ['autodesk', 'CAD', 'electronics', 'eagle'],
        handle: 'vnVtmKd5TNecBFiCow1z',
    },
    Hive: {
        name: 'Hive',
        id: '-M5CNXL0m7wxrwoQiI1-',
        url: 'https://cdn.filestackcontent.com/8zl72D1oTGu1YsHCLr0U',
        handle: '8zl72D1oTGu1YsHCLr0U',
    },
    Kafka: {
        name: 'Kafka',
        id: '-M5CNXL0m7wxrwoQiI10',
        url: 'https://cdn.filestackcontent.com/FabokFfAQUCPQkcteVNL',
        handle: 'FabokFfAQUCPQkcteVNL',
    },
    Solr: {
        name: 'Solr',
        id: '-M5CNXL0m7wxrwoQiI11',
        url: 'https://cdn.filestackcontent.com/bQayPdyBTIC5pkTgS35i',
        handle: 'bQayPdyBTIC5pkTgS35i',
    },
    Spark: {
        name: 'Spark',
        id: '-M5CNXL0m7wxrwoQiI12',
        url: 'https://cdn.filestackcontent.com/Hgr2mZVkSSWZjtk8CAWr',
        handle: 'Hgr2mZVkSSWZjtk8CAWr',
    },
    Hbase: {
        name: 'Hbase',
        id: '-M5CNXL1Gm6J_sIkj1uf',
        url: 'https://cdn.filestackcontent.com/jqxWl3etSzyA5QQLzR7y',
        handle: 'jqxWl3etSzyA5QQLzR7y',
    },
    Mantis: {
        name: 'Mantis',
        id: '-M5CNXL1Gm6J_sIkj1ug',
        url: 'https://cdn.filestackcontent.com/alw3jjmWQtet4mAPUOPT',
        handle: 'alw3jjmWQtet4mAPUOPT',
    },
    SharePoint: {
        name: 'SharePoint',
        id: '-M5CNXL1Gm6J_sIkj1uh',
        url: 'https://cdn.filestackcontent.com/jEhnUsHbRvCwmJcMExnX',
        handle: 'jEhnUsHbRvCwmJcMExnX',
    },
    Lucene: {
        name: 'Lucene',
        id: '-M5CNXL1Gm6J_sIkj1ui',
        url: 'https://cdn.filestackcontent.com/W5cG6qqfTXOPmZsaqivH',
        handle: 'W5cG6qqfTXOPmZsaqivH',
    },
    Nutch: {
        name: 'Nutch',
        id: '-MDJQF5YD7iPdhQvXECR',
        url: 'https://cdn.filestackcontent.com/QkLhQ6CcTRObHvb9sqF7',
        handle: 'QkLhQ6CcTRObHvb9sqF7',
    },
    Pig: {
        name: 'Pig',
        id: '-M5CNXL1Gm6J_sIkj1uk',
        url: 'https://cdn.filestackcontent.com/WRSgDyC4TViHmLzkdALe',
        tags: ['tag n°1', 'tag n°2', 'tag n°3'],
        handle: 'WRSgDyC4TViHmLzkdALe',
    },
    'Tableau Software': {
        name: 'Tableau Software',
        id: '-M5CNXL1Gm6J_sIkj1ul',
        url: 'https://cdn.filestackcontent.com/IcHyclRS5SjktPHLEKOK',
        tags: ['tag n°1', 'tag n°2', 'tag n°3'],
        handle: 'IcHyclRS5SjktPHLEKOK',
    },
    Talend: {
        name: 'Talend',
        id: '-M5CNXL1Gm6J_sIkj1um',
        url: 'https://cdn.filestackcontent.com/WB8NZP1hRC5Y56GdLGjB',
        tags: ['tag n°1', 'tag n°2', 'tag n°3'],
        handle: 'WB8NZP1hRC5Y56GdLGjB',
    },
    'VMware Automation': {
        name: 'VMware Automation',
        id: '-M5CNXL1Gm6J_sIkj1un',
        url: 'https://cdn.filestackcontent.com/uGH62gwVQ5aaP39y6Ob5',
        handle: 'uGH62gwVQ5aaP39y6Ob5',
    },
    'VMware Horizon': {
        name: 'VMware Horizon',
        id: '-M5CNXL1Gm6J_sIkj1uo',
        url: 'https://cdn.filestackcontent.com/fqOXk7RCR5Wmapcbfez4',
        handle: 'fqOXk7RCR5Wmapcbfez4',
    },
    'VMware NSX-T': {
        name: 'VMware NSX-T',
        id: '-M5CNXL1Gm6J_sIkj1up',
        url: 'https://cdn.filestackcontent.com/UrQ7m3wDRtK8OQUGK9Lg',
        handle: 'UrQ7m3wDRtK8OQUGK9Lg',
    },
    'VMware Operations': {
        name: 'VMware Operations',
        id: '-M5CNXL1Gm6J_sIkj1uq',
        url: 'https://cdn.filestackcontent.com/R2LRKANTQwaErEyqJnPU',
        tags: ['tag n°1', 'tag n°2', 'tag n°3'],
        handle: 'R2LRKANTQwaErEyqJnPU',
    },
    'VMware Orchestrator': {
        name: 'VMware Orchestrator',
        id: '-M5CNXL1Gm6J_sIkj1ur',
        url: 'https://cdn.filestackcontent.com/9BzrS9R7C5wrmQAfqsaQ',
        tags: ['tag n°1', 'tag n°2', 'tag n°3'],
        handle: '9BzrS9R7C5wrmQAfqsaQ',
    },
    'VMware vSAN': {
        name: 'VMware vSAN',
        id: '-M5CNXL1Gm6J_sIkj1us',
        url: 'https://cdn.filestackcontent.com/Tj9Y22G2QCuHeA7qSzNe',
        tags: ['tag n°1', 'tag n°2', 'tag n°3'],
        handle: 'Tj9Y22G2QCuHeA7qSzNe',
    },
    'VMware PKS': {
        name: 'VMware PKS',
        id: '-M5CNXL1Gm6J_sIkj1ut',
        url: 'https://cdn.filestackcontent.com/1y3jk0JFRcPo8pMPaTeQ',
        handle: '1y3jk0JFRcPo8pMPaTeQ',
    },
    'VMware vCloud': {
        name: 'VMware vCloud',
        id: '-M5CNXL1Gm6J_sIkj1uu',
        url: 'https://cdn.filestackcontent.com/eaFcCjgnQFutGk9kSLXR',
        handle: 'eaFcCjgnQFutGk9kSLXR',
    },
    'VMware vSphere': {
        name: 'VMware vSphere',
        id: '-M5CNXL1Gm6J_sIkj1uv',
        url: 'https://cdn.filestackcontent.com/KmpiSeGDTTyoUmTwpYbU',
        handle: 'KmpiSeGDTTyoUmTwpYbU',
    },
    NUXT: {
        name: 'NUXT',
        id: '-M5CNXL1Gm6J_sIkj1uw',
        url: 'https://cdn.filestackcontent.com/cFj294GQZiSR4th8UkjL',
        tags: ['vue'],
        handle: 'cFj294GQZiSR4th8UkjL',
    },
    Flutter: {
        name: 'Flutter',
        id: '-M5CNXL1Gm6J_sIkj1ux',
        url: 'https://cdn.filestackcontent.com/J3JQydYuQCedQsuhIaEN',
        tags: ['mobile', 'web', 'desktop'],
        handle: 'J3JQydYuQCedQsuhIaEN',
    },
    Spring: {
        name: 'Spring',
        id: '-M5CNXL1Gm6J_sIkj1uy',
        url: 'https://cdn.filestackcontent.com/s8R07DQnSKSuwzdP1JTO',
        handle: 's8R07DQnSKSuwzdP1JTO',
    },
    'Spring Boot': {
        name: 'Spring Boot',
        id: '-M5CNXL1Gm6J_sIkj1uz',
        url: 'https://cdn.filestackcontent.com/4DSbQFonR1man5U9pHXj',
        tags: ['Spring Boot'],
        handle: '4DSbQFonR1man5U9pHXj',
    },
    Quarkus: {
        name: 'Quarkus',
        id: '-M5CNXL1Gm6J_sIkj1v-',
        url: 'https://cdn.filestackcontent.com/K1q6Vz3RNS6BnAfl6Zv8',
        handle: 'K1q6Vz3RNS6BnAfl6Zv8',
    },
    Hibernate: {
        name: 'Hibernate',
        id: '-M5CNXL1Gm6J_sIkj1v0',
        url: 'https://cdn.filestackcontent.com/l0WgHDttQ1m1YFrT5ves',
        handle: 'l0WgHDttQ1m1YFrT5ves',
    },
    Redux: {
        name: 'Redux',
        id: '-M5CNXL1Gm6J_sIkj1v1',
        url: 'https://cdn.filestackcontent.com/QXR5ehlER9aGXEmOzeuG',
        handle: 'QXR5ehlER9aGXEmOzeuG',
    },
    Electron: {
        name: 'Electron',
        id: '-M5CNXL1Gm6J_sIkj1v2',
        url: 'https://cdn.filestackcontent.com/GWohyiiZRSKQEOLBRiGq',
        handle: 'GWohyiiZRSKQEOLBRiGq',
    },
    PLSQL: {
        name: 'PLSQL',
        id: '-M5CNXL1Gm6J_sIkj1v3',
        url: 'https://cdn.filestackcontent.com/qsGtxJrQSuemr2In9dGr',
        handle: 'qsGtxJrQSuemr2In9dGr',
    },
    'Microsoft SQL Server': {
        name: 'Microsoft SQL Server',
        id: '-M5CNXL1Gm6J_sIkj1v4',
        url: 'https://cdn.filestackcontent.com/vSoGD2J0TilqZhS9bM0E',
        handle: 'vSoGD2J0TilqZhS9bM0E',
    },
    Oracle: {
        name: 'Oracle',
        id: '-M5CNXL1Gm6J_sIkj1v5',
        url: 'https://cdn.filestackcontent.com/AXqJiwetQq6kxDLhRIi4',
        handle: 'AXqJiwetQq6kxDLhRIi4',
    },
    Babel: {
        name: 'Babel',
        id: '-M5CNXL1Gm6J_sIkj1v6',
        url: 'https://cdn.filestackcontent.com/KRLbrvFBTquMeKHZ6IL8',
        handle: 'KRLbrvFBTquMeKHZ6IL8',
    },
    Expo: {
        name: 'Expo',
        id: '-M5CNXL1Gm6J_sIkj1v7',
        url: 'https://cdn.filestackcontent.com/IF4n4Fh7SBx9XxDzNLkw',
        handle: 'IF4n4Fh7SBx9XxDzNLkw',
    },
    Jest: {
        name: 'Jest',
        id: '-M5CNXL1Gm6J_sIkj1v8',
        url: 'https://cdn.filestackcontent.com/sW9XbCGyQtCrsiPp73Qq',
        handle: 'sW9XbCGyQtCrsiPp73Qq',
    },
    Unity: {
        name: 'Unity',
        id: '-M5CNXL1Gm6J_sIkj1v9',
        url: 'https://cdn.filestackcontent.com/No6ZnWSHT2wzSH08PUdl',
        handle: 'No6ZnWSHT2wzSH08PUdl',
    },
    Actionscript: {
        name: 'Actionscript',
        id: '-M5CNXL1Gm6J_sIkj1vA',
        url: 'https://cdn.filestackcontent.com/8CjhBIfsSIGLiWAfCOvV',
        handle: '8CjhBIfsSIGLiWAfCOvV',
    },
    Delphi: {
        name: 'Delphi',
        id: '-M5CNXL1Gm6J_sIkj1vB',
        url: 'https://cdn.filestackcontent.com/gedO4ljtRVywI3Qy1QGJ',
        handle: 'gedO4ljtRVywI3Qy1QGJ',
    },
    Pascal: {
        name: 'Pascal',
        id: '-M5CNXL2nqPNvg7YqU-U',
        url: 'https://cdn.filestackcontent.com/onC5WLPHSMOvUOOAgo6L',
        handle: 'onC5WLPHSMOvUOOAgo6L',
    },
    SQLite: {
        name: 'SQLite',
        id: '-M5CNXL2nqPNvg7YqU-V',
        url: 'https://cdn.filestackcontent.com/0W6gonMeSBOH4pCCHFqD',
        handle: '0W6gonMeSBOH4pCCHFqD',
    },
    JUnit: {
        name: 'JUnit',
        id: '-M5CNXL2nqPNvg7YqU-W',
        url: 'https://cdn.filestackcontent.com/PLY54AvgQAGdjJU1TnHd',
        handle: 'PLY54AvgQAGdjJU1TnHd',
    },
    PHPUnit: {
        name: 'PHPUnit',
        id: '-M5CNXL2nqPNvg7YqU-X',
        url: 'https://cdn.filestackcontent.com/XAx3ACGpSXSobkgAeAOh',
        handle: 'XAx3ACGpSXSobkgAeAOh',
    },
    NUnit: {
        name: 'NUnit',
        id: '-M5CNXL2nqPNvg7YqU-Y',
        url: 'https://cdn.filestackcontent.com/fKAQxUvdTXOgwhuyOaol',
        handle: 'fKAQxUvdTXOgwhuyOaol',
    },
    'ASP dot-net': {
        name: 'ASP dot-net',
        id: '-M5CNXL2nqPNvg7YqU-Z',
        url: 'https://cdn.filestackcontent.com/KIhzvyISFuLQXeHlV2LF',
        handle: 'KIhzvyISFuLQXeHlV2LF',
    },
    Gatsby: {
        name: 'Gatsby',
        id: '-M5CNXL2nqPNvg7YqU-_',
        url: 'https://cdn.filestackcontent.com/jdeISN4QRGe56onQZJAl',
        handle: 'jdeISN4QRGe56onQZJAl',
    },
    'Power BI': {
        name: 'Power BI',
        id: '-M5CNXL2nqPNvg7YqU-a',
        url: 'https://cdn.filestackcontent.com/fQtVeXaT26pwvji6bEWB',
        handle: 'fQtVeXaT26pwvji6bEWB',
    },
    Bash: {
        name: 'Bash',
        id: '-M5CNy-SPrq2Eou5kmMd',
        url: 'https://cdn.filestackcontent.com/yN5pgDjaTZuuILoN58db',
        tags: ['linux'],
        handle: 'yN5pgDjaTZuuILoN58db',
    },
    'Warp 10': {
        name: 'Warp 10',
        id: '-M8Vsf1eQKhamGx8a5vR',
        url: 'https://cdn.filestackcontent.com/PWF6kgk0Sv67ILYAPF6b',
        handle: 'PWF6kgk0Sv67ILYAPF6b',
    },
    Faveod: {
        name: 'Faveod',
        id: '-MA_ciqEDCMvMs7O3TVr',
        url: 'https://cdn.filestackcontent.com/EfPKF8ubQQahwypjs5xY',
        handle: 'EfPKF8ubQQahwypjs5xY',
    },
    Akka: {
        name: 'Akka',
        id: '-MAa8cq57Ng9ZP-S5x0r',
        url: 'https://cdn.filestackcontent.com/8lHforI9QXqRGDQ20Dot',
        handle: '8lHforI9QXqRGDQ20Dot',
    },
    'Next JS': {
        name: 'Next JS',
        id: '-MB9Rn4nbUef0HnmU-gG',
        url: 'https://cdn.filestackcontent.com/X00NjzZScyjhHfmHb2UA',
        tags: ['React'],
        handle: 'X00NjzZScyjhHfmHb2UA',
    },
    'Visual Basic': {
        name: 'Visual Basic',
        id: '-MBDmUntvk_y789iIpE2',
        url: 'https://cdn.filestackcontent.com/qKA0Et3qTyqUhHJLzhnv',
        handle: 'qKA0Et3qTyqUhHJLzhnv',
    },
    Splunk: {
        name: 'Splunk',
        id: '-MBDmjPBQVAoIwBdUAXM',
        url: 'https://cdn.filestackcontent.com/EJeDnUniQ6OnigiUFbvS',
        handle: 'EJeDnUniQ6OnigiUFbvS',
    },
    Qt: {
        name: 'Qt',
        id: '-MBdcGs7dr6NoYArQgVk',
        url: 'https://cdn.filestackcontent.com/hIgO4G5Tm6QIIIRtqCw0',
        tags: ['c', 'c++', 'gui'],
        handle: 'hIgO4G5Tm6QIIIRtqCw0',
    },
    TensorFlow: {
        name: 'TensorFlow',
        id: '-MBhCyRLkFNsKRNx1ALF',
        url: 'https://cdn.filestackcontent.com/a753NdHQZWFhrUtAk2Dw',
        tags: ['TensorFlow', 'Tensor Flow', 'machine learning'],
        handle: 'a753NdHQZWFhrUtAk2Dw',
    },
    Dart: {
        name: 'Dart',
        id: '-MBhjjg6uO0-HCUf_hfp',
        url: 'https://cdn.filestackcontent.com/0Odm1opiSwmBC3kzrZoS',
        handle: '0Odm1opiSwmBC3kzrZoS',
    },
    'Vert.x': {
        name: 'Vert.x',
        id: '-MC1Ncvdkytpk_iZGpnu',
        url: 'https://cdn.filestackcontent.com/BDUTwBdZSrOhwC03u8f5',
        tags: ['reactive', 'rx'],
        handle: 'BDUTwBdZSrOhwC03u8f5',
    },
    Blender: {
        name: 'Blender',
        id: '-MCGTyBq9LqS5vr-QNly',
        url: 'https://cdn.filestackcontent.com/6iYEFGIxTBCF3BW6Eju8',
        handle: '6iYEFGIxTBCF3BW6Eju8',
    },
    'Hyper V': {
        name: 'Hyper V',
        id: '-MCpheNYvqnOPmRbLEEM',
        url: 'https://cdn.filestackcontent.com/H36I5mCSvK311WRIYAE1',
        tags: ['microsoft', 'hyper v'],
        handle: 'H36I5mCSvK311WRIYAE1',
    },
    GraphQL: {
        name: 'GraphQL',
        id: '-MCuaoo8gcI4vBSZO92p',
        url: 'https://cdn.filestackcontent.com/adkU9PS06lEHMTwUhQIA',
        tags: ['database', 'rest', 'api'],
        handle: 'adkU9PS06lEHMTwUhQIA',
    },
    ReasonML: {
        name: 'ReasonML',
        id: '-MCwEJG1hhkDJVIgedBL',
        url: 'https://cdn.filestackcontent.com/3sfKkP6HR5a4LDnz2Ha7',
        tags: ['fp', 'reason', 'react'],
        handle: '3sfKkP6HR5a4LDnz2Ha7',
    },
    Jira: {
        name: 'Jira',
        id: '-MDFIADaitJ24kP8X59m',
        url: 'https://cdn.filestackcontent.com/czaS5r1IQGOioIykV5Gi',
        tags: ['project'],
        handle: 'czaS5r1IQGOioIykV5Gi',
    },
    'Microsoft project': {
        name: 'Microsoft project',
        id: '-MDFIFo65gF_4nFuvdbJ',
        url: 'https://cdn.filestackcontent.com/bTyWg3fhQE6qXtoTcUGL',
        handle: 'bTyWg3fhQE6qXtoTcUGL',
    },
    'Oracle E-Business Suite': {
        name: 'Oracle E-Business Suite',
        id: '-MDFJ05oxNyeCB732rKz',
        url: 'https://cdn.filestackcontent.com/6vrJabIQXa7okayzs9AQ',
        tags: ['erp'],
        handle: '6vrJabIQXa7okayzs9AQ',
    },
    Twig: {
        name: 'Twig',
        id: '-MDJP5B3Jsg_4GRIGTzn',
        url: 'https://cdn.filestackcontent.com/hwYYuzXDRDqGH9B7LWjW',
        tags: ['php', 'templating'],
        handle: 'hwYYuzXDRDqGH9B7LWjW',
    },
    cassandra: {
        name: 'cassandra',
        id: '-MDO5x621A2PxTFa8Rrq',
        url: 'https://cdn.filestackcontent.com/mpXz5GheSnqBlSwMfqPp',
        tags: ['bdd'],
        handle: 'mpXz5GheSnqBlSwMfqPp',
    },
    'Apache Beam': {
        name: 'Apache Beam',
        id: '-MEwMw8Inm0g1syn4LoV',
        url: 'https://cdn.filestackcontent.com/JlLnxXnIQBa6pDmFR2gs',
        handle: 'JlLnxXnIQBa6pDmFR2gs',
    },
    'Apache Airflow': {
        name: 'Apache Airflow',
        id: '-MEwN2rDXEcKL_gyN3FQ',
        url: 'https://cdn.filestackcontent.com/ny7CLo2Tk2AuYYCK7JQL',
        handle: 'ny7CLo2Tk2AuYYCK7JQL',
    },
    Nativescript: {
        name: 'Nativescript',
        id: '-MEwN7dYYbD4nDtMd-13',
        url: 'https://cdn.filestackcontent.com/91Y5N0RTBymFAjWDeQAo',
        handle: '91Y5N0RTBymFAjWDeQAo',
    },
    Loopback: {
        name: 'Loopback',
        id: '-MF-fZUnJ5i72XgmhDV2',
        url: 'https://cdn.filestackcontent.com/jORa7gd7TaOUWUoJejkC',
        tags: ['js', 'ts', 'typescript', 'node.js', 'rest', 'openapi', 'graphql'],
        handle: 'jORa7gd7TaOUWUoJejkC',
    },
    Pytorch: {
        name: 'Pytorch',
        id: '-MF-ygXjOUGPCoJa3v7v',
        url: 'https://cdn.filestackcontent.com/El2PexpyS8S7UgR2qB3I',
        tags: ['ml'],
        handle: 'El2PexpyS8S7UgR2qB3I',
    },
    LLVM: {
        name: 'LLVM',
        id: '-MF-yzK1uAyV1Cxd3gEJ',
        url: 'https://cdn.filestackcontent.com/7ljTObTTSKcRYXEd7k4Q',
        tags: ['VM', 'Java'],
        handle: '7ljTObTTSKcRYXEd7k4Q',
    },
    Crystal: {
        name: 'Crystal',
        id: '-MF-z9wmwRJydgQWv1NM',
        url: 'https://cdn.filestackcontent.com/tgW8IPgXTZGcrccvmM4U',
        handle: 'tgW8IPgXTZGcrccvmM4U',
    },
    'F#': {
        name: 'F#',
        id: '-MFny1oJ3T1vG0gRv3sr',
        url: 'https://cdn.filestackcontent.com/qTWZZyRSukqCog45gEAr',
        tags: ['ocaml', '.net', 'microsoft'],
        handle: 'qTWZZyRSukqCog45gEAr',
    },
    Neo4J: {
        name: 'Neo4J',
        id: '-MG8xpIbIs6Z1QBPchIo',
        url: 'https://cdn.filestackcontent.com/KvnXGiSL6LL7ZUuhrnA0',
        tags: ['graph', 'db', 'database', 'bdd', 'base de données', 'data', 'données'],
        handle: 'KvnXGiSL6LL7ZUuhrnA0',
    },
    MAUI: {
        name: 'MAUI',
        id: '-MGOG9kyDgS1OBv53PZ0',
        url: 'https://cdn.filestackcontent.com/xwKJaDb6QEymLSMydkcP',
        handle: 'xwKJaDb6QEymLSMydkcP',
    },
    'Xamarin.Forms': {
        name: 'Xamarin.Forms',
        id: '-M5CNXL0m7wxrwoQiI8_',
        url: 'https://cdn.filestackcontent.com/UUNf1TD0Tby7VNxsk2pK',
        tags: ['Android'],
        handle: 'UUNf1TD0Tby7VNxsk2pK',
    },
    DynamoDB: {
        name: 'DynamoDB',
        id: '-MHAO5qBi07wJeKAM129',
        url: 'https://cdn.filestackcontent.com/sEc5isFXRRGJZIFTwujE',
        tags: ['db', 'aws', 'amazon'],
        handle: 'sEc5isFXRRGJZIFTwujE',
    },
    Traefik: {
        name: 'Traefik',
        id: '-MHWTqwL7rlnu326htWw',
        url: 'https://cdn.filestackcontent.com/PXUDqE61S3a9BprL4AIS',
        tags: ['go', 'ops', 'reverse', 'proxy'],
        handle: 'PXUDqE61S3a9BprL4AIS',
    },
    Progress: {
        name: 'Progress',
        id: '-MHuAPh5uyhNHVve6oCb',
        url: 'https://cdn.filestackcontent.com/RJK9U64VQUCBpUaWOqwE',
        tags: ['open edge', 'openedge', 'sql', 'db'],
        handle: 'RJK9U64VQUCBpUaWOqwE',
    },
    SolidWorks: {
        name: 'SolidWorks',
        id: '-MI-QmlwA-Oc1StUs3oT',
        url: 'https://cdn.filestackcontent.com/RgwVm0luTrSuUyMo5bdR',
        tags: ['3d'],
        handle: 'RgwVm0luTrSuUyMo5bdR',
    },
    Informatica: {
        name: 'Informatica',
        id: '-MIPQ40EcRzdUaFBogDa',
        url: 'https://cdn.filestackcontent.com/fNDrfPs9T1KaCcvlVkgs',
        tags: ['etl', 'informatica'],
        handle: 'fNDrfPs9T1KaCcvlVkgs',
    },
    'SAS Visual Analytics': {
        name: 'SAS Visual Analytics',
        id: '-MJ1dXkJsDmkINLSMBkL',
        url: 'https://cdn.filestackcontent.com/KvtSwSTSmWF3eDZrhobX',
        tags: ['dataviz', 'data'],
        handle: 'KvtSwSTSmWF3eDZrhobX',
    },
    'Windows OS': {
        name: 'Windows OS',
        id: '-MJCeW1NNrctbldOVMav',
        url: 'https://cdn.filestackcontent.com/8HmteSuQteFRRFiINvgw',
        tags: ['Windows', 'WindowsOS'],
        handle: '8HmteSuQteFRRFiINvgw',
    },
    'Linux System': {
        name: 'Linux System',
        id: '-MJCdI8fjj7cC-XmNoc-',
        url: 'https://cdn.filestackcontent.com/XzsVgd31RkXGr5bmm6TB',
        tags: ['Linux'],
        handle: 'XzsVgd31RkXGr5bmm6TB',
    },
    'macOS (system)': {
        name: 'macOS (system)',
        id: '-MJCecTX2Fc-HzR0OxCk',
        url: 'https://cdn.filestackcontent.com/T6LywkDQTJqgKv0dq0XT',
        tags: ['macOS', 'OSX', 'OS X'],
        handle: 'T6LywkDQTJqgKv0dq0XT',
    },
    Boost: {
        name: 'Boost',
        id: '-MJCe9INCCQAqtxipIat',
        url: 'https://cdn.filestackcontent.com/uQdE5WiTmy8ilW7KTkpQ',
        handle: 'uQdE5WiTmy8ilW7KTkpQ',
    },
    Wayland: {
        name: 'Wayland',
        id: '-MJCeSpQWzj3TohlQng9',
        url: 'https://cdn.filestackcontent.com/IaaVKCeQOWbIKCpmsJZc',
        tags: ['Unix'],
        handle: 'IaaVKCeQOWbIKCpmsJZc',
    },
    Cocoa: {
        name: 'Cocoa',
        id: '-MJCeci3IzN4vUi4RmKx',
        url: 'https://cdn.filestackcontent.com/wpd3pgPbSdSYdlcNNNOP',
        tags: ['apple', 'macos'],
        handle: 'wpd3pgPbSdSYdlcNNNOP',
    },
    'Unix Server': {
        name: 'Unix Server',
        id: '-MJCetT7IN3YwukLWgu7',
        url: 'https://cdn.filestackcontent.com/XzsVgd31RkXGr5bmm6TB',
        tags: ['adminsys', 'systems', 'unix'],
        handle: 'XzsVgd31RkXGr5bmm6TB',
    },
    'Kali Linux': {
        name: 'Kali Linux',
        id: '-MK-KWeb5cw15f_ponCD',
        url: 'https://cdn.filestackcontent.com/ImzcMJ50ToaAOOpn1flW',
        tags: ['security', 'pentest', 'pentesting'],
        handle: 'ImzcMJ50ToaAOOpn1flW',
    },
    Jenkins: {
        name: 'Jenkins',
        id: '-MK0CuS1hl-E2PWyH9gm',
        url: 'https://cdn.filestackcontent.com/WMjzgZG9SMqD6rTEoa3W',
        tags: ['Jenkins', 'Jenkins CI', 'Hudson'],
        handle: 'WMjzgZG9SMqD6rTEoa3W',
    },
    IoT: {
        name: 'IoT',
        id: '-MK9XdQxm8LwQFRlALed',
        url: 'https://cdn.filestackcontent.com/Icx7RWA0TAQ95WtFq3WQ',
        tags: ['embedded', 'arduino', 'embarqué', 'raspberry'],
        handle: 'Icx7RWA0TAQ95WtFq3WQ',
    },
    Svelte: {
        name: 'Svelte',
        id: '-MKZStGv127OGDpbvmRV',
        url: 'https://cdn.filestackcontent.com/PQS962THTA2JAv4o9BCL',
        tags: ['component', 'web'],
        handle: 'PQS962THTA2JAv4o9BCL',
    },
    Nest: {
        name: 'Nest',
        id: '-MKiOva_p_asNZ3NRBhn',
        url: 'https://cdn.filestackcontent.com/BkA3oNhASWmV51LAPGHZ',
        tags: ['js', 'javascript'],
        handle: 'BkA3oNhASWmV51LAPGHZ',
    },
    Hasura: {
        name: 'Hasura',
        id: '-MLI8H85266j8YvqqlDv',
        url: 'https://cdn.filestackcontent.com/ppHQc4JRQJedZ6lRphop',
        tags: ['Graphql'],
        handle: 'ppHQc4JRQJedZ6lRphop',
    },
    Zoho: {
        name: 'Zoho',
        id: '-MLLqZOMxLKnN5LOnDQD',
        url: 'https://cdn.filestackcontent.com/SC92sU3XQn67iCG61fES',
        tags: ['CRM'],
        handle: 'SC92sU3XQn67iCG61fES',
    },
    RxJava: {
        name: 'RxJava',
        id: '-MMQ-A-J0YXxM-mBdqkF',
        url: 'https://cdn.filestackcontent.com/0ccJOBwgRuCrtiAZTVaa',
        tags: ['reactive', 'java', 'rx'],
        handle: '0ccJOBwgRuCrtiAZTVaa',
    },
    RxKotlin: {
        name: 'RxKotlin',
        id: '-MMQ-KoeFatA5yfW49K2',
        url: 'https://cdn.filestackcontent.com/oFFEFctyTimLTmF1yqK9',
        tags: ['rx', 'kotlin', 'mobile'],
        handle: 'oFFEFctyTimLTmF1yqK9',
    },
    Mulesoft: {
        name: 'Mulesoft',
        id: '-MVHnlj1dNc2ACV_JCbv',
        url: 'https://cdn.filestackcontent.com/07YQcfOlRF2wX6xlnySX',
        tags: ['esb'],
        handle: '07YQcfOlRF2wX6xlnySX',
    },
    VHDL: {
        name: 'VHDL',
        id: '-MVRfDlCbH1d4-vCLntn',
        url: 'https://cdn.filestackcontent.com/VgTyyHGeTp6OoExFnGEj',
        tags: ['electronics', 'electronique', 'VHISC', 'hardware'],
        handle: 'VgTyyHGeTp6OoExFnGEj',
    },
    Postman: {
        name: 'Postman',
        id: '-MWcFNg-W6JDHlVQWrp-',
        url: 'https://cdn.filestackcontent.com/ns2gtMTURUmLROayKwWs',
        tags: ['postman', 'http'],
        handle: 'ns2gtMTURUmLROayKwWs',
    },
    Cypress: {
        name: 'Cypress',
        id: '-MWcH26xezq4LltVWaH9',
        url: 'https://cdn.filestackcontent.com/jr6FDT0MQKOye3GuvSMd',
        tags: ['Cy', 'Cypress'],
        handle: 'jr6FDT0MQKOye3GuvSMd',
    },
    SÉLÉNIUM: {
        name: 'SÉLÉNIUM',
        id: '-MWcIDeHcuHy3grMaskM',
        url: 'https://cdn.filestackcontent.com/O04briOKSCeKlyFca5c1',
        tags: ['sélé', 'qa'],
        handle: 'O04briOKSCeKlyFca5c1',
    },
    Android: {
        name: 'Android',
        id: '-M5CNXKwXM41mKYGHF4P',
        url: 'https://cdn.filestackcontent.com/cxno5zXSS7GJamCw5j4I',
        tags: ['os'],
        handle: 'cxno5zXSS7GJamCw5j4I',
    },
    ZeroMQ: {
        name: 'ZeroMQ',
        id: '-MWyGxd2CKX7ux6UvBz0',
        url: 'https://cdn.filestackcontent.com/GHKTYrAS6FWv8Jj4VZQ1',
        tags: ['zqm', 'queue'],
        handle: 'GHKTYrAS6FWv8Jj4VZQ1',
    },
    Ada: {
        name: 'Ada',
        id: '-MX2h4g0nXVbiMyp2oW-',
        url: 'https://cdn.filestackcontent.com/PbiRwD4eRK7TxlcHbOcb',
        tags: ['aeronautics'],
        handle: 'PbiRwD4eRK7TxlcHbOcb',
    },
    Vault: {
        name: 'Vault',
        id: '-MX7AZZb9_QKxxlnC07x',
        url: 'https://cdn.filestackcontent.com/9I5LfL80Rbsj71sn5kqI',
        tags: ['password', 'iam'],
        handle: '9I5LfL80Rbsj71sn5kqI',
    },
    GSAP: {
        name: 'GSAP',
        id: '-MXGeMPMiW0-ufU33C6e',
        url: 'https://cdn.filestackcontent.com/zFKm3xpXQsWg9ZF2lQWp',
        tags: ['animations', 'greensock'],
        handle: 'zFKm3xpXQsWg9ZF2lQWp',
    },
    'Bubble.io': {
        name: 'Bubble.io',
        id: '-MXfk0_I2ciJ1ynQ3IXD',
        url: 'https://cdn.filestackcontent.com/aFzniSL7RbCQTme9Fxzo',
        handle: 'aFzniSL7RbCQTme9Fxzo',
    },
    Scilab: {
        name: 'Scilab',
        id: '-MXg5tyrYqcYZMMvMWYQ',
        url: 'https://cdn.filestackcontent.com/rOiOxhozQt2uZtOMm6WN',
        tags: ['math'],
        handle: 'rOiOxhozQt2uZtOMm6WN',
    },
    Ahrefs: {
        name: 'Ahrefs',
        id: '-MXgzRdUrFDljxJ3e6-q',
        url: 'https://cdn.filestackcontent.com/QFVgqSDRpWwAGoTGjV0Q',
        tags: ['seo'],
        handle: 'QFVgqSDRpWwAGoTGjV0Q',
    },
    'Recoil.js': {
        name: 'Recoil.js',
        id: '-MY3vzqpHbjLxpHJF185',
        url: 'https://cdn.filestackcontent.com/uAW8zUyvRj6ezt6kLigS',
        tags: ['data', 'redux', 'management'],
        handle: 'uAW8zUyvRj6ezt6kLigS',
    },
    'Tailwind CSS': {
        name: 'Tailwind CSS',
        id: '-MY9XFTUp2LViiBNinwU',
        url: 'https://cdn.filestackcontent.com/dy82SztOSReiP4mTkN8P',
        tags: ['css', 'framework', 'ui'],
        handle: 'dy82SztOSReiP4mTkN8P',
    },
    'Oracle Forms': {
        name: 'Oracle Forms',
        id: '-MYJofeVLnpg8GD5peCt',
        url: 'https://cdn.filestackcontent.com/AXqJiwetQq6kxDLhRIi4',
        tags: ['oracle', 'ui'],
        handle: 'AXqJiwetQq6kxDLhRIi4',
    },
    'Oracle Reports': {
        name: 'Oracle Reports',
        id: '-MYJosuDx3RwgHjFKlT-',
        url: 'https://cdn.filestackcontent.com/AXqJiwetQq6kxDLhRIi4',
        tags: ['sql', 'db', 'dataviz'],
        handle: 'AXqJiwetQq6kxDLhRIi4',
    },
    Salesforce: {
        name: 'Salesforce',
        id: '-MYtpcgoamSjRXmkiLcO',
        url: 'https://cdn.filestackcontent.com/un5bU2HuSvqNrvAfr1ME',
        handle: 'un5bU2HuSvqNrvAfr1ME',
    },
    Stambia: {
        name: 'Stambia',
        id: '-MZIRZUDsyLkRHekPJ5m',
        url: 'https://cdn.filestackcontent.com/MkNbX1f4RMKLvq3JqU9y',
        tags: ['etl', 'data'],
        handle: 'MkNbX1f4RMKLvq3JqU9y',
    },
    Selenium: {
        name: 'Selenium',
        id: '-MZSf7UbxhKaLZKtjYc4',
        url: 'https://cdn.filestackcontent.com/opLK7KETamaG0stu2oAV',
        handle: 'opLK7KETamaG0stu2oAV',
    },
    Iterop: {
        name: 'Iterop',
        id: '-MZSqGz2bstym_angtta',
        url: 'https://cdn.filestackcontent.com/nKgcuOx5TfqFtOhkypSo',
        handle: 'nKgcuOx5TfqFtOhkypSo',
    },
    Solidity: {
        name: 'Solidity',
        id: '-M_UV3DXcY8H0_gT7IDg',
        url: 'https://cdn.filestackcontent.com/0DIGGFaTESm1EDBiOIYQ',
        tags: ['Blockchain'],
        handle: '0DIGGFaTESm1EDBiOIYQ',
    },
    WebGL: {
        name: 'WebGL',
        id: '-Ma2OpSuccAoIAETK5sC',
        url: 'https://cdn.filestackcontent.com/HCspGkQgTwaf6GxYhFdg',
        tags: ['js', '3D', 'opengl'],
        handle: 'HCspGkQgTwaf6GxYhFdg',
    },
    'Babylon.js': {
        name: 'Babylon.js',
        id: '-Ma2PClw-se1rw8DiQ2F',
        url: 'https://cdn.filestackcontent.com/RnvqRcTaaYdie9PdMw1w',
        tags: ['webgl', 'js'],
        handle: 'RnvqRcTaaYdie9PdMw1w',
    },
    JHipster: {
        name: 'JHipster',
        id: '-Mac0gKqoXY8co5pKwFk',
        url: 'https://cdn.filestackcontent.com/uvI9fUL9Qdu2EgwHY8GP',
        tags: ['bootstraping', 'app'],
        handle: 'uvI9fUL9Qdu2EgwHY8GP',
    },
    'OpenAPI / Swagger': {
        name: 'OpenAPI / Swagger',
        id: '-MamEEpWGvevgQuFQsdl',
        url: 'https://cdn.filestackcontent.com/57wccTZmZhj2se9YegQk',
        tags: ['OAI', 'swagger'],
        handle: '57wccTZmZhj2se9YegQk',
    },
    AsyncAPI: {
        name: 'AsyncAPI',
        id: '-MamETJ1Dy7UU_MTqmUg',
        url: 'https://cdn.filestackcontent.com/i9PBGhuYSmW1TosCrOdm',
        tags: ['event', 'driven', 'api'],
        handle: 'i9PBGhuYSmW1TosCrOdm',
    },
    OAuth: {
        name: 'OAuth',
        id: '-MamEjHT2S-icxAdz_ef',
        url: 'https://cdn.filestackcontent.com/aT0liIRMQGcUiGSXuqAY',
        tags: ['jwt', 'token', 'api'],
        handle: 'aT0liIRMQGcUiGSXuqAY',
    },
    OIDC: {
        name: 'OIDC',
        id: '-MamF-I_Ib9n-2IsRrmk',
        url: 'https://cdn.filestackcontent.com/3Az7QtL7RLarfKutC96A',
        tags: ['openid', 'connect', 'api'],
        handle: '3Az7QtL7RLarfKutC96A',
    },
    JWT: {
        name: 'JWT',
        id: '-MamFDjEPXVimH1nB_CA',
        url: 'https://cdn.filestackcontent.com/OuOJcZ7S5e10zPqWXo6g',
        tags: ['json', 'web', 'tokens', 'api', 'oauth'],
        handle: 'OuOJcZ7S5e10zPqWXo6g',
    },
    JSONSchema: {
        name: 'JSONSchema',
        id: '-MamFQ-_Vrhw0fx2hN4_',
        url: 'https://cdn.filestackcontent.com/y6l9JphvQByfpballPbQ',
        tags: ['json', 'api', 'validation'],
        handle: 'y6l9JphvQByfpballPbQ',
    },
    Kong: {
        name: 'Kong',
        id: '-MamFmdDaheXFLUVVbKA',
        url: 'https://cdn.filestackcontent.com/bmmnt2IhQbq4bzbUZVyc',
        tags: ['api', 'microservices'],
        handle: 'bmmnt2IhQbq4bzbUZVyc',
    },
    WebRTC: {
        name: 'WebRTC',
        id: '-Mank-gGjc5CweGLc2DT',
        url: 'https://cdn.filestackcontent.com/v42K5WQMShyY9sodRi3m',
        tags: ['visio'],
        handle: 'v42K5WQMShyY9sodRi3m',
    },
    odoo: {
        name: 'odoo',
        id: '-Mbk0hdCIV2sLT_-id-A',
        url: 'https://cdn.filestackcontent.com/3bfgsNLSnyWbEasadQD7',
        tags: ['erp', 'openerp'],
        handle: '3bfgsNLSnyWbEasadQD7',
    },
    'Ember.js': {
        name: 'Ember.js',
        id: '-Mcj493CIaLUqLmczyra',
        url: 'https://cdn.filestackcontent.com/n7CxZHxSQXGl1qTMeEzv',
        handle: 'n7CxZHxSQXGl1qTMeEzv',
    },
    Pug: {
        name: 'Pug',
        id: '-MdGaeIjp2t0cP6-ndx_',
        url: 'https://cdn.filestackcontent.com/KFHvDf3QR2vKbRAVCoQg',
        tags: ['template'],
        handle: 'KFHvDf3QR2vKbRAVCoQg',
    },
    Shopify: {
        name: 'Shopify',
        id: '-MdGspqKSDUF4Vm8ZXKg',
        url: 'https://cdn.filestackcontent.com/9yXMjQr0T8CVNAl7U4Lw',
        handle: '9yXMjQr0T8CVNAl7U4Lw',
    },
    '.NET core': {
        name: '.NET core',
        id: '-MdWB6z5Ri9xj8BdM29o',
        url: 'https://cdn.filestackcontent.com/SaYL9GYaRBWwbyxWDPEp',
        tags: ['.net', 'dot', 'net', 'c#'],
        handle: 'SaYL9GYaRBWwbyxWDPEp',
    },
    Groovy: {
        name: 'Groovy',
        id: '-MdX8DQAOLF_-wLZQGjg',
        url: 'https://cdn.filestackcontent.com/JDrE3M1EReC8T68kejZo',
        tags: ['Java', 'jvm'],
        handle: 'JDrE3M1EReC8T68kejZo',
    },
    UiPath: {
        name: 'UiPath',
        id: '-Me4B-U7-piAU4s--DDx',
        url: 'https://cdn.filestackcontent.com/36AxhBrbTEqjD0csl1jh',
        tags: ['automation'],
        handle: '36AxhBrbTEqjD0csl1jh',
    },
    Sketch: {
        name: 'Sketch',
        id: '-Me8wcnfPSH49fQGeX1u',
        url: 'https://cdn.filestackcontent.com/wD6oBnoIQbOq33rvhaP8',
        tags: ['ui', 'ux', 'design'],
        handle: 'wD6oBnoIQbOq33rvhaP8',
    },
    Figma: {
        name: 'Figma',
        id: '-Me8xA9fq02qdHtp8av-',
        url: 'https://cdn.filestackcontent.com/WckwBt5hSEa6tHcsp63Y',
        tags: ['ux', 'design'],
        handle: 'WckwBt5hSEa6tHcsp63Y',
    },
    Miro: {
        name: 'Miro',
        id: '-Me8xgwcSIcqlmnElUzo',
        url: 'https://cdn.filestackcontent.com/nDsFyyOPQ7WwtxMCJMHx',
        tags: ['design'],
        handle: 'nDsFyyOPQ7WwtxMCJMHx',
    },
    WebMethods: {
        name: 'WebMethods',
        id: '-MeU07RYsWLIiScrwrje',
        url: 'https://cdn.filestackcontent.com/lZRFZP2QdqlJM7TlMThf',
        tags: ['software ag'],
        handle: 'lZRFZP2QdqlJM7TlMThf',
    },
    Storybook: {
        name: 'Storybook',
        id: '-Mf7P1w9iKJhfYDVtlrS',
        url: 'https://cdn.filestackcontent.com/Km46CyTk6avMFR6PxhPA',
        tags: ['ui', 'testing', 'design system'],
        handle: 'Km46CyTk6avMFR6PxhPA',
    },
    'Google Apps Script': {
        name: 'Google Apps Script',
        id: '-MflTNcqB68N5ChhileZ',
        url: 'https://cdn.filestackcontent.com/7AMEKORSYqA3MByBXYpn',
        tags: ['js', 'google docs', 'javascript'],
        handle: '7AMEKORSYqA3MByBXYpn',
    },
    'AWS Infinidash': {
        name: 'AWS Infinidash',
        id: '-MgHCRjeUDQ6n-3IEnmw',
        url: 'https://cdn.filestackcontent.com/Cz648FkCQMyMVe6oApT2',
        handle: 'Cz648FkCQMyMVe6oApT2',
    },
    'Tibco EBX': {
        name: 'Tibco EBX',
        id: '-Mhru-9m8yTYdQ-1-PNT',
        url: 'https://cdn.filestackcontent.com/z8MFUxx4QSLUeY6bdb3Y',
        handle: 'z8MFUxx4QSLUeY6bdb3Y',
    },
    ArgoCD: {
        name: 'ArgoCD',
        id: '-Mi6UY0wEa5yZOT_Ag_E',
        url: 'https://cdn.filestackcontent.com/QAMHDLPrQ8CJeHZn05IU',
        handle: 'QAMHDLPrQ8CJeHZn05IU',
    },
    Hugo: {
        name: 'Hugo',
        id: '-Mi732CTVHfR9DFOZPr3',
        url: 'https://cdn.filestackcontent.com/8vGJ15SjRMCtAjzZCIpR',
        handle: '8vGJ15SjRMCtAjzZCIpR',
    },
    'Azure Devops': {
        name: 'Azure Devops',
        id: '-MiQV_5zID7CUDIl4Hwz',
        url: 'https://cdn.filestackcontent.com/JCJrvU3VSNKpwO3MyH2D',
        tags: ['ops', 'cloud'],
        handle: 'JCJrvU3VSNKpwO3MyH2D',
    },
    ReactQuery: {
        name: 'ReactQuery',
        id: '-Mib5luMK6uQTKj1LoDR',
        url: 'https://cdn.filestackcontent.com/hYSWK3zGRNOpixA1nTX9',
        tags: ['react', 'redux', 'state', 'management'],
        handle: 'hYSWK3zGRNOpixA1nTX9',
    },
    'Event Store': {
        name: 'Event Store',
        id: '-MiuSLAqO32eJNW-PtpN',
        url: 'https://cdn.filestackcontent.com/MltY2RBESkG6SjhaxwQa',
        tags: ['event', 'sourcing'],
        handle: 'MltY2RBESkG6SjhaxwQa',
    },
    Sentry: {
        name: 'Sentry',
        id: '-MiuSwdioZ3ItKPKYe5H',
        url: 'https://cdn.filestackcontent.com/MBUQkXreQVOPin9bodOd',
        tags: ['errors', 'checking'],
        handle: 'MBUQkXreQVOPin9bodOd',
    },
    Packer: {
        name: 'Packer',
        id: '-MiuTBGzL0X0S_I72Y9n',
        url: 'https://cdn.filestackcontent.com/J78gUWCR6mi3eg53rBbd',
        handle: 'J78gUWCR6mi3eg53rBbd',
    },
    SwiftUI: {
        name: 'SwiftUI',
        id: '-Mj-JjncvZQT0kGi8NbQ',
        url: 'https://cdn.filestackcontent.com/bGr5A9lzQQPHnalJLOkk',
        tags: ['cocoa touch', 'cocoa'],
        handle: 'bGr5A9lzQQPHnalJLOkk',
    },
    D3: {
        name: 'D3',
        id: '-MjYVWLoZZML6owebKS5',
        url: 'https://cdn.filestackcontent.com/bynFURc5CkEQTWTmvgQS',
        tags: ['ibm', 'bull'],
        handle: 'bynFURc5CkEQTWTmvgQS',
    },
    Vuetify: {
        name: 'Vuetify',
        id: '-MjeLGU0fuiFMR19Ssia',
        url: 'https://cdn.filestackcontent.com/np4kfcGdSgSKPHmWdban',
        tags: ['front', 'material ', 'vuejs'],
        handle: 'np4kfcGdSgSKPHmWdban',
    },
    Quasar: {
        name: 'Quasar',
        id: '-MjeLYGImBBZgjRV550B',
        url: 'https://cdn.filestackcontent.com/5HpLXqQ8T5A3g0a5zIde',
        tags: ['vue', 'framework'],
        handle: '5HpLXqQ8T5A3g0a5zIde',
    },
    ESLint: {
        name: 'ESLint',
        id: '-MjhyGXzDKTgxILBTH4L',
        url: 'https://cdn.filestackcontent.com/ul5YS9tISwCKHijqg5EN',
        tags: ['tooling'],
        handle: 'ul5YS9tISwCKHijqg5EN',
    },
    Asana: {
        name: 'Asana',
        id: '-Mk1l85RdII-JhnRWQPN',
        url: 'https://cdn.filestackcontent.com/5e3nt2ZhQa6OMpBcQd0B',
        handle: '5e3nt2ZhQa6OMpBcQd0B',
    },
    Webflow: {
        name: 'Webflow',
        id: '-Mk8bqmniJBxaZmN8Ggt',
        url: 'https://cdn.filestackcontent.com/etGgbXBPS8qCHhjrY4t4',
        handle: 'etGgbXBPS8qCHhjrY4t4',
    },
    RxSwift: {
        name: 'RxSwift',
        id: '-MkfdXQpHkBVhZGEj4VA',
        url: 'https://cdn.filestackcontent.com/oFFEFctyTimLTmF1yqK9',
        tags: ['reactive', 'rx', 'mobile'],
        handle: 'oFFEFctyTimLTmF1yqK9',
    },
    FastAPI: {
        name: 'FastAPI',
        id: '-MkfeMsIQwyCQRmfB_-A',
        url: 'https://cdn.filestackcontent.com/VQjS9i8PTwKKA3JsoXev',
        tags: ['api', 'flask'],
        handle: 'VQjS9i8PTwKKA3JsoXev',
    },
};

export const technologies: Technology[] = Object.values(rawData);
